minigames:
  TNT_RUN:
    display_name: "§cTNT Run"
    icon: "TNT"
    minPlayers: 2
    maxPlayers: 4
    lore:
      - "§7Run over the TNT platform."
      - "§7Last one standing wins!"
    enabled_modes:
      - CLASSIC
      - HARDCORE
      - TIMED

  BED_WARS:
    display_name: "§bBed Wars"
    icon: "BEDROCK"
    lore:
      - "§7Protect your bed, destroy others."
      - "§7Team up or go solo!"
    enabled_modes:
      - SOLO
      - TEAMS
      - HARDCORE

  SKY_WARS:
    display_name: "§eSky Wars"
    icon: "ENDER_PEARL"
    lore:
      - "§7Battle on floating islands."
      - "§7Gather loot, be last alive!"
    enabled_modes:
      - SOLO
      - TEAMS
      - INSANE

  SPLEEF:
    display_name: "§dSpleef"
    icon: "DIAMOND_SHOVEL"
    lore:
      - "§7Break blocks beneath opponents."
      - "§7Last man standing wins!"
    enabled_modes:
      - CLASSIC
      - TEAMS

  TTT:
    display_name: "§5Trouble In Terrorist Town"
    icon: BOW
    lore:
      - "§7Find the traitors before it's too late."
      - "§7Keep your eyes open!"
    minPlayers: 4
    maxPlayers: 16
    enabled_modes:
      - CLASSIC

  RACE:
    display_name: '&eKart Racing'
    icon: BOAT
    lore:
      - '&7Race your friends in high-speed karts!'
    minPlayers: 2
    maxPlayers: 16
    enabled_modes:
      - CLASSIC

  # ... add more minigames here ...
arenas:
  tnt_run:
    schematic: "tnt_run.schem"
    flags:
      BLOCK_BREAK: DENY
      BLOCK_PLACE: DENY
      PVP: ALLOW
  bed_wars:
    schematic: "bed_wars.schem"
    flags:
      BLOCK_BREAK: DENY
      BLOCK_PLACE: DENY
      PVP: ALLOW

party:
  maxSize: 4                    # must be ≥ 1
  inviteTimeoutSeconds: 30      # must be ≥ 1
  allowCrossWorld: true         # whether invites work across worlds

stats:
  storage: flatfile             # or "mysql"
  flatfileFolder: "player-stats"  # if using flatfile
  # mysql:                       # only required if storage: mysql
  #   host: "localhost"
  #   port: 3306
  #   database: "minigames"
  #   user: "root"
  #   password: ""
  leaderboard:
    enabled: true
    size: 10
  autoSaveIntervalSeconds: 60