name: MinigamesPlugin
main: com.auroraschaos.minigames.MinigamesPlugin
version: 1.0.0
api-version: 1.21
author: AurorasChaos

commands:
  minigames:
    description: Main command for minigames (join, leave, stats, etc.)
    usage: /minigames <subcommand>
    permission: minigames.play
  mgui:
    description: Opens the Minigames GUI
    usage: /mgui
    permission: minigames.play
  party:
    description: Manage parties
    usage: /party <subcommand>
    permission: minigames.party

permissions:
  minigames.admin:
    description: Access to all admin commands.
    default: op
  minigames.play:
    description: Allows players to join and play minigames.
    default: true
  minigames.party:
    description: Allows players to create and manage parties.
    default: true

softdepend: [PlaceholderAPI, Citizens, Multiverse-Core]
